source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'OznerLibrarySwiftyDemo' do
    pod 'DateTools'
    pod 'MQTTKit'
    pod 'SQLite.swift'
    pod 'SwiftyJSON'
end

